### ISSUE TITLE
':' mapped to '_' when using str.encode() in Python 3.9b5.

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/precis_i18n#10]
From Issue #9 

======================================================================
ERROR: test_golden_json (test_golden.TestGolden)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/precis-i18n-1.0.1_p20190922/work/precis_i18n-1498def50914b8d4f670874cc282072790619399/test/test_golden.py", line 28, in test_golden_json
    self.check_disallow(profile, input_, error)
  File "/var/tmp/portage/dev-python/precis-i18n-1.0.1_p20190922/work/precis_i18n-1498def50914b8d4f670874cc282072790619399/test/test_golden.py", line 50, in check_disallow
    input_.encode(profile)
LookupError: unknown encoding: UsernameCaseMapped:ToLower

To fix this, get_profile will map ':' to '_'. This means that "UsernameCaseMapped_ToLower" will also work starting in next release.

**Comment by byllyfish** [comment]
Fixed in release 1.0.2.
