### ISSUE TITLE
Travis test_golden_json fails under pypy3.5-5.10.1 due to CaseFold bug

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/precis_i18n#5]
The test failure is due to a bug in pypy 3.5 casefolding for Cherokee characters. This bug is fixed in a coming pypy3 release:

https://bitbucket.org/pypy/pypy/issues/2857

```
ᏚᎢᎵᎬᎢᎬᏒ: UnicodeEncodeError('UsernameCaseMapped:CaseFold', '\uabaa\uab72\uab85\uab7c\uab72\uab7c\uaba2', 0, 7, 'DISALLOWED/not_idempotent')

======================================================================
ERROR: test_golden_json (test.test_golden.TestGolden)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/byllyfish/precis_i18n/test/test_golden.py", line 24, in test_golden_json
    self.check_allow(profile, input_, output)
  File "/home/travis/build/byllyfish/precis_i18n/test/test_golden.py", line 30, in check_allow
    actual = input_.encode(profile).decode('utf-8')
  File "/home/travis/build/byllyfish/precis_i18n/precis_i18n/codec.py", line 11, in _encode
    return (profile.enforce(s).encode('utf-8'), len(s))
  File "/home/travis/build/byllyfish/precis_i18n/precis_i18n/profile.py", line 65, in enforce
    temp = self.idempotence_check(temp)
  File "/home/travis/build/byllyfish/precis_i18n/precis_i18n/profile.py", line 157, in idempotence_check
    raise_error(self.name, value, -1, 'not_idempotent')
  File "/home/travis/build/byllyfish/precis_i18n/precis_i18n/baseclass.py", line 103, in raise_error
    raise UnicodeEncodeError(encoding, value, start, end, reason)
UnicodeEncodeError: 'UsernameCaseMapped:CaseFold' codec can't encode characters in position 0-6: DISALLOWED/not_idempotent
```

**Comment by byllyfish** [comment]
Fixed in pypy3.5-7.0.0:
