### ISSUE TITLE
Tests Source

### ISSUE THREAD

**Issue by justinba1010** [byllyfish/precis_i18n#7]
I was just wondering where/how the tests in `golden.json` were generated. We are using your project to test against, and we're down to only failing 38 inputs in `golden.json`.

**Comment by byllyfish** [comment]
`golden.json` is generated by the test/make_golden.py script, using test/golden_source.txt as the input. Note that the make_golden.py script uses the precis_i18n python code, not another implementation or standard. If there's a latent bug, some results could be wrong.

golden_source.txt contains some comments which might pinpoint what an input is trying to test. What inputs do you see failing in your project?

**Comment by justinba1010** [comment]
Sorry for the late reply, I went on vacation. I am sure theres probably a few issues on our side as well, but these are the inputs `bs-precis` doesn't match on.
```
  ● Golden Tests › UsernameCasePreserved Test: rul·lz	Codepoints: [114, 117, 108, 183, 108, 122]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › UsernameCasePreserved Test: ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

  bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › UsernameCasePreserved Test: أ٠١٢٣٤٥٦٧٨٩	Codepoints: [1571, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › UsernameCasePreserved Test: أ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1571, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › UsernameCasePreserved Test: ΨϓΧΗ	Codepoints: [936, 979, 935, 919]

    bs-precis do not raise an exception
    precis_i18n does

  ● Golden Tests › UsernameCaseMapped Test: iİıI	Codepoints: [105, 304, 305, 73]

    precis_i18n: "ii̇ıi"
    bs-precis: "iiıi"

  ● Golden Tests › UsernameCaseMapped Test: rul·lz	Codepoints: [114, 117, 108, 183, 108, 122]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › UsernameCaseMapped Test: ruL·Lz	Codepoints: [114, 117, 76, 183, 76, 122]

 bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › UsernameCaseMapped Test: ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › UsernameCaseMapped Test: أ٠١٢٣٤٥٦٧٨٩	Codepoints: [1571, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › UsernameCaseMapped Test: أ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1571, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › UsernameCaseMapped Test: ΨϓΧΗ	Codepoints: [936, 979, 935, 919]

       bs-precis do not raise an exception
    precis_i18n does

  ● Golden Tests › OpaqueString Test: 🄚evin	Codepoints: [127258, 56602, 101, 118, 105, 110]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: 🄺evin	Codepoints: [127290, 56634, 101, 118, 105, 110]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: 🅚evin	Codepoints: [127322, 56666, 101, 118, 105, 110]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: 🅺evin	Codepoints: [127354, 56698, 101, 118, 105, 110]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: 🇺🇸	Codepoints: [127482, 56826, 127480, 56824]

   bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: 👾	Codepoints: [128126, 56446]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: 💚	Codepoints: [128154, 56474]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: rul·lz	Codepoints: [114, 117, 108, 183, 108, 122]

   bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: ٠١٢٣٤٥٦٧٨٩	Codepoints: [1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641]

   bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: أ٠١٢٣٤٥٦٧٨٩	Codepoints: [1571, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › OpaqueString Test: أ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1571, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

   bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: 🄚evin	Codepoints: [127258, 56602, 101, 118, 105, 110]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: 🄺evin	Codepoints: [127290, 56634, 101, 118, 105, 110]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: 🅚evin	Codepoints: [127322, 56666, 101, 118, 105, 110]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: 🅺evin	Codepoints: [127354, 56698, 101, 118, 105, 110]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: iİıI	Codepoints: [105, 304, 305, 73]

    expect(bs-precis).toBe(precis_i18n) // Object.is equality

    precis_i18n: "ii̇ıi"
    bs-precis: "iiıi"

      at affirm (node_modules/@glennsl/bs-jest/lib/js/src/jest.js:72:40)
      at Object.<anonymous> (node_modules/@glennsl/bs-jest/lib/js/src/jest.js:249:11)

  ● Golden Tests › NicknameCaseMapped Test: 🇺🇸	Codepoints: [127482, 56826, 127480, 56824]

   bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: 👾	Codepoints: [128126, 56446]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: 💚	Codepoints: [128154, 56474]

   bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: rul·lz	Codepoints: [114, 117, 108, 183, 108, 122]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: ruL·Lz	Codepoints: [114, 117, 76, 183, 76, 122]

    bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: ٠١٢٣٤٥٦٧٨٩	Codepoints: [1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641]

   bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

  bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: أ٠١٢٣٤٥٦٧٨٩	Codepoints: [1571, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641]

  bs-precis raise an exception
    precis_i18n does not

  ● Golden Tests › NicknameCaseMapped Test: أ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1571, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

      bs-precis raise an exception
    precis_i18n does not
```

**Comment by justinba1010** [comment]
I went ahead and did `  ● Golden Tests › OpaqueString Test: 🄚evin	Codepoints: [127258, 56602, 101, 118, 105, 110]` by hand. I got that it fails because codepoint `56602` is disallowed by [RFC 5892 Page 60](https://tools.ietf.org/html/rfc5892).

**Comment by SamWhited** [comment]
In case you're interested, something like this can be used to run these same tests against the Go version. There are some inconsistencies, and I've disabled some of the profiles that aren't standard. I haven't attempted to verify if this is a bug in my code, or in one or the other precis libraries yet, but hopefully it's useful to you as well:

https://gist.github.com/SamWhited/9b94379d1d5d17dc772dd2310dfd1d68

**Comment by byllyfish** [comment]
Thanks. For some inputs, it looks like the 32-bit (non-BMP) code point is being split into a UTF-16 surrogate pair. This makes sense if your underlying runtime is JavaScript, which uses UTF-16 for all strings. You may need to do an additional step of verifying the UTF-16 and re-combining surrogate pairs.

This affects the Kevin's, the flag, and the emoji's.

Some of the other inputs have CONTEXTO code points.

```
● Golden Tests › UsernameCasePreserved Test: rul·lz	Codepoints: [114, 117, 108, 183, 108, 122]

    bs-precis raises an exception
    precis_i18n does not

**183 is the middle dot which is CONTEXTO. It is allowed between two L's.**

  ● Golden Tests › UsernameCasePreserved Test: ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

  bs-precis raises an exception
    precis_i18n does not

**These are extended arabic-indic digits (CONTEXTO) which are okay as long as they don't appear in the same string as arabic-indic digits.**

  ● Golden Tests › UsernameCasePreserved Test: أ٠١٢٣٤٥٦٧٨٩	Codepoints: [1571, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641]

    bs-precis raises an exception
    precis_i18n does not

**These are arabic-indic digits (CONTEXTO) which are okay as long as they don't appear in the same string as extended arabic-indic digits.**

  ● Golden Tests › UsernameCasePreserved Test: أ۰۱۲۳۴۵۶۷۸۹	Codepoints: [1571, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785]

    bs-precis raises an exception
    precis_i18n does not

**These are extended arabic-indic digits (CONTEXTO) which are okay as long as they don't appear in the same string as arabic-indic digits.**
```

I need to look more at these two...

```
● Golden Tests › UsernameCasePreserved Test: ΨϓΧΗ	Codepoints: [936, 979, 935, 919]

    bs-precis does not raises an exception
    precis_i18n does

**UnicodeEncodeError: 'UsernameCaseMapped' codec can't encode character '\u03d3' in position 1: DISALLOWED/has_compat**

  ● Golden Tests › UsernameCaseMapped Test: iİıI	Codepoints: [105, 304, 305, 73]

    precis_i18n: "ii̇ıi"
    bs-precis: "iiıi"

**This may be a locale or programming language dependency. Dotted-i has a locale-specific case mapping, but PRECIS is locale-independent.**
```

**Comment by byllyfish** [comment]
```
● Golden Tests › UsernameCasePreserved Test: ΨϓΧΗ	Codepoints: [936, 979, 935, 919]

    bs-precis does not raises an exception
    precis_i18n does

UnicodeEncodeError: 'UsernameCasePreserved' codec can't encode character '\u03d3' in position 1: DISALLOWED/has_compat
```

I'm seeing that the second character of 'ΨϓΧΗ' ('\u03d3') has a compatibility equivalent so it is not PVALID.

unicodedata.normalize('NFKC', '\u03d3') == '\u038e'

**Comment by justinba1010** [comment]
Definitely. Thank you both, I'll definitely take a look into both of those. I believe the codepoints were identical in numeric value in UTF 8/16/32. But it's possibly an encoding issue.
